### ISSUE TITLE
NPM Readme 

### ISSUE THREAD

**Issue by alechp** [bretthayes/bendy#1]
Need new minor publish to NPM. 

Example install on NPM shows "limber" instead of "bendy":

--------------------------

![screen shot 2016-11-21 at 9 26 58 am](https://cloud.githubusercontent.com/assets/3058939/20493199/b1de1d52-afcc-11e6-9f0a-a7d8d4ac1cd4.png)

**Comment by bretthayes** [comment]
Thanks for noticing this @alechp. Pushed a patch since it's just a typo.
